// ============================================================
// data.js — Mock data & shared helpers for User Interface
// ============================================================
const _d = (n) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split("T")[0];
};

export const currentUser = {
  id: "u001",
  name: "Budi Santoso",
  nip: "198501012010011001",
  username: "budi.santoso",
  email: "budi.santoso@pelindo.co.id",
  phone: "081234567890",
  role_code: "user",
  entity_code: "ENT001",
  entity_name: "PT Maju Bersama",
  branch_code: "SBY",
  branch_name: "Cabang Surabaya",
  avatar: null,
};

export const assetsMock = [
  {
    id: "ast001",
    name: "Laptop Dell Latitude 5520",
    category: "LAPTOP",
    brand: "Dell",
    model: "Latitude 5520",
    serial: "SN-DL-001234",
    location: "Ruang IT - Lantai 3",
    branch_code: "SBY",
    // Riwayat terakhir: trx004 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 18500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-1135G7",
      ram: "16 GB DDR4",
      storage: "512 GB SSD NVMe",
      display: '15.6" FHD IPS',
      os: "Windows 11 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 63Wh",
      weight: "1.76 kg",
    },
  },
  {
    id: "ast002",
    name: "Laptop HP EliteBook 840 G8",
    category: "LAPTOP",
    brand: "HP",
    model: "EliteBook 840 G8",
    serial: "SN-HP-005678",
    location: "Ruang IT - Lantai 3",
    branch_code: "SBY",
    // trx007 ACTIVE — dipinjam Budi Santoso sejak 10 Feb 2025, jatuh tempo 20 Feb 2025 (TERLAMBAT)
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 16750000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
    spec: {
      cpu: "Intel Core i7-1165G7",
      ram: "16 GB DDR4",
      storage: "256 GB SSD",
      display: '14" FHD IPS',
      os: "Windows 10 Pro",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 53Wh",
      weight: "1.46 kg",
    },
  },
  {
    id: "ast007",
    name: "Laptop ASUS ExpertBook B1500",
    category: "LAPTOP",
    brand: "ASUS",
    model: "ExpertBook B1500",
    serial: "SN-AS-011234",
    location: "Ruang HR - Lantai 2",
    branch_code: "SBY",
    // Riwayat terakhir: trx017 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 14200000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-1235U",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "2-Cell 42Wh",
      weight: "1.8 kg",
    },
  },
  {
    id: "ast008",
    name: "Laptop Lenovo ThinkPad X1 Carbon",
    category: "LAPTOP",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 9",
    serial: "SN-LN-015678",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    // trx019 ACTIVE — dipinjam Joko Santoso, jatuh tempo 20 Mar 2026 (masih dalam masa pinjam)
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 24500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80",
    spec: {
      cpu: "Intel Core i7-1165G7",
      ram: "16 GB LPDDR4x",
      storage: "1 TB SSD NVMe",
      display: '14" 2K IPS',
      os: "Windows 10 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 57Wh",
      weight: "1.13 kg",
    },
  },
  {
    id: "ast009",
    name: "Laptop Toshiba Satellite L745",
    category: "LAPTOP",
    brand: "Toshiba",
    model: "Satellite L745",
    serial: "SN-TS-099001",
    location: "Gudang - Lantai 1",
    branch_code: "SBY",
    // dihapus dari inventaris setelah evaluasi kondisi DAMAGED
    status: "DELETED",
    condition: "DAMAGED",
    year: 2013,
    price: 4500000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=400&q=80",
    spec: {
      cpu: "Intel Core i3-2330M",
      ram: "4 GB DDR3",
      storage: "500 GB HDD",
      display: '14" HD',
      os: "Windows 7 (EOL)",
      gpu: "Intel HD 3000",
    },
  },
  {
    id: "ast010",
    name: "Laptop Acer Aspire 5 A515",
    category: "LAPTOP",
    brand: "Acer",
    model: "Aspire 5 A515-56",
    serial: "SN-AC-022345",
    location: "Ruang Marketing - Lantai 2",
    branch_code: "SBY",
    // trx025 dikembalikan kondisi MINOR_DAMAGE oleh Budi Santoso → Super Admin ubah ke MAINTENANCE (4 Mar 2026)
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2022,
    price: 9800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-1135G7",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 48Wh",
      weight: "1.9 kg",
    },
  },
  {
    id: "ast011",
    name: "Laptop MacBook Pro 14 M2",
    category: "LAPTOP",
    brand: "Apple",
    model: "MacBook Pro 14-inch M2",
    serial: "SN-AP-033456",
    location: "Ruang Desain - Lantai 3",
    branch_code: "SBY",
    // Riwayat terakhir: trx027 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 32000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1611186871525-8778f68f8f1c?w=400&q=80",
    spec: {
      cpu: "Apple M2 Pro 10-core",
      ram: "16 GB Unified",
      storage: "512 GB SSD",
      display: '14.2" Liquid Retina XDR',
      os: "macOS Ventura",
      gpu: "Apple M2 Pro 16-core GPU",
      battery: "70Wh",
      weight: "1.6 kg",
    },
  },
  {
    id: "ast012",
    name: "Laptop MSI Modern 14",
    category: "LAPTOP",
    brand: "MSI",
    model: "Modern 14 B11SBU",
    serial: "SN-MS-044567",
    location: "Ruang Finance - Lantai 2",
    branch_code: "SBY",
    // trx028b ACTIVE — perbaikan layar setelah trx028 dikembalikan kondisi MINOR_DAMAGE
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2021,
    price: 11500000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-1155G7",
      ram: "8 GB DDR4",
      storage: "512 GB NVMe SSD",
      display: '14" FHD IPS',
      os: "Windows 11 Home",
      gpu: "NVIDIA GeForce MX450",
      battery: "3-Cell 52Wh",
      weight: "1.4 kg",
    },
  },
  {
    id: "ast013",
    name: "Laptop Dell XPS 13",
    category: "LAPTOP",
    brand: "Dell",
    model: "XPS 13 9310",
    serial: "SN-DL-055678",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    // Riwayat terakhir: trx029 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 22000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?w=400&q=80",
    spec: {
      cpu: "Intel Core i7-1185G7",
      ram: "16 GB LPDDR4x",
      storage: "512 GB SSD",
      display: '13.4" FHD+ Touch',
      os: "Windows 11 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 52Wh",
      weight: "1.2 kg",
    },
  },
  {
    id: "ast014",
    name: "Laptop HP Pavilion 15",
    category: "LAPTOP",
    brand: "HP",
    model: "Pavilion 15-eg2000",
    serial: "SN-HP-066789",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx032 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 10500000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-1235U",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD IPS',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 41Wh",
      weight: "1.75 kg",
    },
  },

  // ── DESKTOP ────────────────────────────────────────────────
  {
    id: "ast003",
    name: "Desktop PC Lenovo ThinkCentre M720",
    category: "DESKTOP",
    brand: "Lenovo",
    model: "ThinkCentre M720",
    serial: "SN-LN-009012",
    location: "Ruang Operasional - Lantai 2",
    branch_code: "SBY",
    // Riwayat terakhir: trx009 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 12000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-9400",
      ram: "8 GB DDR4",
      storage: "1 TB HDD + 256 GB SSD",
      display: "N/A (Desktop)",
      os: "Windows 10 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.1, HDMI, DP",
      form: "Tower",
    },
  },
  {
    id: "ast015",
    name: "Desktop PC HP ProDesk 400 G7",
    category: "DESKTOP",
    brand: "HP",
    model: "ProDesk 400 G7",
    serial: "SN-HP-077890",
    location: "Ruang Akuntansi - Lantai 2",
    branch_code: "SBY",
    // Riwayat terakhir: trx034 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 10800000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&q=80",
    spec: {
      cpu: "Intel Core i5-10500",
      ram: "8 GB DDR4",
      storage: "256 GB SSD",
      os: "Windows 10 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.2, HDMI, DP",
      form: "Micro Tower",
    },
  },
  {
    id: "ast016",
    name: "Desktop PC Dell OptiPlex 7090",
    category: "DESKTOP",
    brand: "Dell",
    model: "OptiPlex 7090",
    serial: "SN-DL-088901",
    location: "Ruang Legal - Lantai 3",
    branch_code: "SBY",
    // Riwayat terakhir: trx035 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 13500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=400&q=80",
    spec: {
      cpu: "Intel Core i7-10700",
      ram: "16 GB DDR4",
      storage: "512 GB SSD",
      os: "Windows 11 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.2, HDMI, DP, TB4",
      form: "Small Form Factor",
    },
  },
  {
    id: "ast017",
    name: "Desktop PC ASUS Pro E500 G6",
    category: "DESKTOP",
    brand: "ASUS",
    model: "Pro E500 G6",
    serial: "SN-AS-099012",
    location: "Ruang Engineering - Lantai 3",
    branch_code: "SBY",
    // Riwayat terakhir: trx036b — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 15200000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&q=80",
    spec: {
      cpu: "Intel Core i9-10900",
      ram: "32 GB DDR4",
      storage: "1 TB SSD NVMe",
      os: "Windows 10 Pro",
      gpu: "NVIDIA Quadro P620",
      ports: "USB 3.2, HDMI, DP",
      form: "Tower",
    },
  },

  // ── SERVER ─────────────────────────────────────────────────
  {
    id: "ast004",
    name: "Server Dell PowerEdge R740",
    category: "SERVER",
    brand: "Dell",
    model: "PowerEdge R740",
    serial: "SN-SV-000001",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // Riwayat terakhir: trx011 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 185000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80",
    spec: {
      cpu: "2x Intel Xeon Gold 6226R",
      ram: "256 GB DDR4 ECC",
      storage: "8x 2TB SAS RAID",
      os: "Ubuntu Server 22.04",
      network: "4x 1GbE + 2x 10GbE",
      power: "Dual 750W PSU",
      rack: "2U Rack Mount",
      mgmt: "iDRAC9",
    },
  },
  {
    id: "ast018",
    name: "Server HP ProLiant DL380 Gen10",
    category: "SERVER",
    brand: "HP",
    model: "ProLiant DL380 Gen10",
    serial: "SN-SV-000002",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // Riwayat terakhir: trx037 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 210000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=400&q=80",
    spec: {
      cpu: "2x Intel Xeon Silver 4210R",
      ram: "128 GB DDR4 ECC",
      storage: "4x 1.92TB SSD RAID",
      os: "VMware ESXi 7.0",
      network: "4x 1GbE FlexibleLOM",
      power: "Dual 800W PSU",
      rack: "2U Rack",
      mgmt: "iLO5",
    },
  },
  {
    id: "ast019",
    name: "Server IBM System x3650 M5",
    category: "SERVER",
    brand: "IBM",
    model: "System x3650 M5",
    serial: "SN-SV-000003",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // trx039 ACTIVE — perbaikan NIC setelah trx038b dikembalikan kondisi MINOR_DAMAGE oleh Hendra Wijaya
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2018,
    price: 145000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=400&q=80",
    spec: {
      cpu: "2x Intel Xeon E5-2620 v4",
      ram: "64 GB DDR4 ECC",
      storage: "6x 600GB SAS HDD",
      os: "Red Hat Enterprise Linux 8",
      network: "4x 1GbE",
      power: "Dual 900W PSU",
      rack: "2U Rack",
      mgmt: "IMM2",
    },
  },

  // ── NETWORK ────────────────────────────────────────────────
  {
    id: "ast005",
    name: "Switch Cisco Catalyst 2960X-48",
    category: "NETWORK",
    brand: "Cisco",
    model: "Catalyst 2960X-48",
    serial: "SN-NW-002345",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx013 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2019,
    price: 25000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&q=80",
    spec: {
      ports: "48x GbE + 4x SFP+",
      throughput: "176 Gbps",
      poe: "Yes, 740W PoE+",
      vlan: "Up to 4094 VLANs",
      mgmt: "Web, CLI, SNMP",
      rack: "1U Rack",
      memory: "256 MB DRAM",
      flash: "128 MB Flash",
    },
  },
  {
    id: "ast020",
    name: "Router Mikrotik CCR2004",
    category: "NETWORK",
    brand: "Mikrotik",
    model: "CCR2004-1G-12S+2XS",
    serial: "SN-NW-013456",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx040 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 18500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=400&q=80",
    spec: {
      ports: "12x SFP+ + 2x 25G SFP28",
      cpu: "4-core ARM Cortex-A72",
      ram: "4 GB DDR4",
      throughput: "Up to 100 Gbps",
      mgmt: "WinBox, WebFig, SSH",
      rack: "1U Rack",
      os: "RouterOS v7",
    },
  },
  {
    id: "ast021",
    name: "Access Point Ubiquiti UniFi U6 Pro",
    category: "NETWORK",
    brand: "Ubiquiti",
    model: "UniFi U6 Pro",
    serial: "SN-NW-024567",
    location: "Lobby - Lantai 1",
    branch_code: "SBY",
    // trx042 ACTIVE — dipinjam Citra Dewi, jatuh tempo 20 Mar 2026 (masih dalam masa pinjam)
    status: "BORROWED",
    condition: "GOOD",
    year: 2023,
    price: 4200000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
    spec: {
      wifi: "WiFi 6 (802.11ax)",
      bands: "2.4 GHz + 5 GHz",
      speed: "Up to 4.8 Gbps",
      antennas: "6 antennas",
      poe: "802.3at PoE",
      coverage: "~185 m²",
      concurrent: "300+ clients",
    },
  },
  {
    id: "ast022",
    name: "Firewall Fortinet FortiGate 60F",
    category: "NETWORK",
    brand: "Fortinet",
    model: "FortiGate 60F",
    serial: "SN-NW-035678",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx043 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 32000000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1551703599-6b3e8379aa8c?w=400&q=80",
    spec: {
      throughput: "10 Gbps Firewall",
      vpn: "6.5 Gbps IPsec VPN",
      ports: "10x GbE",
      storage: "128 GB SSD",
      mgmt: "FortiOS, FortiManager",
      rack: "Desktop/1U",
    },
  },
  {
    id: "ast023",
    name: "Switch HP Aruba 2930F 24G",
    category: "NETWORK",
    brand: "HP",
    model: "Aruba 2930F 24G",
    serial: "SN-NW-046789",
    location: "Ruang Server - Basement",
    branch_code: "SBY",
    // trx045 ACTIVE — dipinjam Denny Kurniawan sejak 15 Jan 2025, jatuh tempo 25 Jan 2025 (TERLAMBAT)
    status: "BORROWED",
    condition: "GOOD",
    year: 2020,
    price: 14800000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1614624532983-4ce03382d63d?w=400&q=80",
    spec: {
      ports: "24x GbE + 4x SFP+",
      throughput: "128 Gbps",
      poe: "Yes, PoE+",
      vlan: "4094 VLANs",
      mgmt: "Web, CLI, SNMP",
      rack: "1U Rack",
      memory: "512 MB",
    },
  },

  // ── UPS ─────────────────────────────────────────────────────
  {
    id: "ast006",
    name: "UPS APC Smart-UPS 1500VA",
    category: "UPS",
    brand: "APC",
    model: "Smart-UPS 1500VA",
    serial: "SN-UP-007890",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // trx015 ACTIVE — perbaikan baterai setelah trx014 dikembalikan kondisi MINOR_DAMAGE oleh Gunawan Setiawan
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2018,
    price: 8500000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400&q=80",
    spec: {
      capacity: "1500VA / 1000W",
      runtime: "~14 min at full load",
      input: "220-230V AC",
      output: "220-230V AC",
      battery: "24V Lead Acid",
      interface: "USB, Serial",
      mgmt: "APC PowerChute",
      form: "Tower/Rack",
    },
  },
  {
    id: "ast024",
    name: "UPS Eaton 5PX 2200VA",
    category: "UPS",
    brand: "Eaton",
    model: "5PX 2200VA RT2U",
    serial: "SN-UP-018901",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // Riwayat terakhir: trx047 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 14500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=400&q=80",
    spec: {
      capacity: "2200VA / 1980W",
      runtime: "~10 min at full load",
      input: "200-240V AC",
      output: "200-240V AC",
      battery: "Lithium-ion",
      interface: "USB, RS-232, Network Card",
      mgmt: "Eaton Intelligent Power Manager",
      form: "2U Rack",
    },
  },
  {
    id: "ast025",
    name: "UPS CyberPower PR1500ELCDRT2U",
    category: "UPS",
    brand: "CyberPower",
    model: "PR1500ELCDRT2U",
    serial: "SN-UP-029012",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx048b — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 9800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&q=80",
    spec: {
      capacity: "1500VA / 1350W",
      runtime: "~12 min at full load",
      input: "200-240V AC",
      output: "200-240V AC",
      battery: "12V 9Ah x2",
      interface: "USB, RS-232",
      mgmt: "PowerPanel Business",
      form: "2U Rack",
    },
  },
  {
    id: "ast026",
    name: "UPS APC Back-UPS Pro 1200VA",
    category: "UPS",
    brand: "APC",
    model: "Back-UPS Pro BR1200GI",
    serial: "SN-UP-030123",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx049 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 5200000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=400&q=80",
    spec: {
      capacity: "1200VA / 720W",
      runtime: "~20 min at half load",
      input: "220-230V AC",
      output: "220-230V AC",
      battery: "12V Lead Acid",
      interface: "USB",
      mgmt: "APC PowerChute Personal",
      form: "Tower",
    },
  },
  {
    id: "ast027",
    name: "UPS Schneider APC SMT1500I",
    category: "UPS",
    brand: "Schneider",
    model: "APC SMT1500I",
    serial: "SN-UP-041234",
    location: "Server Room - Basement",
    branch_code: "SBY",
    // Riwayat terakhir: trx050 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 11200000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1601462904263-f2fa0c851cb9?w=400&q=80",
    spec: {
      capacity: "1500VA / 1000W",
      runtime: "~16 min at full load",
      input: "230V AC",
      output: "230V AC",
      battery: "24V Lead Acid",
      interface: "USB, SmartSlot",
      mgmt: "PowerChute Network Shutdown",
      form: "Tower/Rack",
    },
  },

  // ── OTHER ────────────────────────────────────────────────────
  {
    id: "ast028",
    name: "Printer HP LaserJet Pro M404n",
    category: "OTHER",
    brand: "HP",
    model: "LaserJet Pro M404n",
    serial: "SN-OT-052345",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx052 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 4800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&q=80",
    spec: {
      type: "Laser Monochrome",
      speed: "40 ppm",
      resolution: "1200 x 1200 dpi",
      paper: "A4, Letter, Legal",
      connect: "USB, LAN",
      memory: "256 MB",
      duty: "80,000 pages/month",
    },
  },
  {
    id: "ast029",
    name: "Monitor LG UltraWide 34WN80C",
    category: "OTHER",
    brand: "LG",
    model: "34WN80C-B",
    serial: "SN-OT-063456",
    location: "Ruang Desain - Lantai 3",
    branch_code: "SBY",
    // trx054_maint ACTIVE — panel retak setelah trx054 dikembalikan kondisi MINOR_DAMAGE oleh Budi Santoso
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2022,
    price: 8500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
    spec: {
      size: '34" Curved IPS',
      resolution: "3440 x 1440 (UWQHD)",
      refresh: "60 Hz",
      response: "5ms",
      hdr: "HDR10",
      connect: "HDMI, USB-C, USB Hub",
      brightness: "300 cd/m²",
    },
  },
  {
    id: "ast030",
    name: "Proyektor Epson EB-X51",
    category: "OTHER",
    brand: "Epson",
    model: "EB-X51",
    serial: "SN-OT-074567",
    location: "Ruang Rapat A - Lantai 2",
    branch_code: "SBY",
    // trx057 ACTIVE — dipinjam Denny Kurniawan sejak 15 Feb 2025, jatuh tempo 17 Feb 2025 (TERLAMBAT)
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 6200000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&q=80",
    spec: {
      brightness: "3800 lumens",
      resolution: "XGA (1024 x 768)",
      ratio: "4:3",
      lamp: "200W",
      lamp_life: "10,000 hours (ECO)",
      connect: "HDMI, VGA, USB",
      throw: "1.48-1.78:1",
    },
  },
  {
    id: "ast031",
    name: "Proyektor Benq MH550",
    category: "OTHER",
    brand: "Benq",
    model: "MH550",
    serial: "SN-OT-085678",
    location: "Ruang Rapat B - Lantai 3",
    branch_code: "SBY",
    // Riwayat terakhir: trx059 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 5800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    spec: {
      brightness: "3500 lumens",
      resolution: "Full HD (1920 x 1080)",
      ratio: "16:9",
      lamp: "240W",
      lamp_life: "8,000 hours (SmartEco)",
      connect: "HDMI, VGA, USB",
      throw: "1.47-1.76:1",
    },
  },
  {
    id: "ast032",
    name: "Scanner Fujitsu fi-7160",
    category: "OTHER",
    brand: "Fujitsu",
    model: "fi-7160",
    serial: "SN-OT-096789",
    location: "Ruang Arsip - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx060 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 12500000,
    budget_type: "CAPEX",
    photo_url:
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&q=80",
    spec: {
      speed: "60 ppm / 120 ipm",
      resolution: "600 dpi optical",
      adf: "80-sheet ADF",
      paper: "A8 - A3",
      connect: "USB 3.0",
      os: "Windows, Mac",
      weight: "2.6 kg",
    },
  },
  {
    id: "ast033",
    name: "Kamera CCTV Hikvision DS-2CD2143G2",
    category: "OTHER",
    brand: "Hikvision",
    model: "DS-2CD2143G2-I",
    serial: "SN-OT-107890",
    location: "Lobby - Lantai 1",
    branch_code: "SBY",
    // trx062 ACTIVE — dipinjam Eko Prasetyo, jatuh tempo 31 Mar 2026 (masih dalam masa pinjam)
    status: "BORROWED",
    condition: "GOOD",
    year: 2023,
    price: 1800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&q=80",
    spec: {
      resolution: "4 MP",
      lens: "2.8mm",
      ir: "60m IR range",
      ip: "IP67 weatherproof",
      h265: "H.265+",
      poe: "PoE (802.3af)",
      features: "AcuSense, Wide Angle",
    },
  },
  {
    id: "ast034",
    name: "NVR Dahua DHI-NVR4116HS-4KS2",
    category: "OTHER",
    brand: "Dahua",
    model: "DHI-NVR4116HS-4KS2",
    serial: "SN-OT-118901",
    location: "Ruang Security - Lantai 1",
    branch_code: "SBY",
    // Riwayat terakhir: trx063 — perbaikan selesai kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 3200000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1562408590-e32931084e23?w=400&q=80",
    spec: {
      channels: "16 IP channels",
      resolution: "Up to 8MP",
      playback: "4-channel 4K",
      hdd: "Up to 8TB",
      network: "2x RJ-45 1GbE",
      connect: "2x USB, 1x HDMI, 1x VGA",
      compression: "H.265+",
    },
  },
  {
    id: "ast035",
    name: "Telepon VOIP Grandstream GXP2160",
    category: "OTHER",
    brand: "Grandstream",
    model: "GXP2160",
    serial: "SN-OT-129012",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    // Riwayat terakhir: trx065 dikembalikan kondisi GOOD → AVAILABLE
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 2800000,
    budget_type: "OPEX",
    photo_url:
      "https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=400&q=80",
    spec: {
      lines: "6 SIP lines",
      keys: "24 programmable BLF keys",
      display: '4.3" Color LCD',
      audio: "HD Audio, Full-duplex",
      connect: "2x GbE, USB",
      poe: "PoE (802.3af)",
      codecs: "G.722, G.711, G.729",
    },
  },
];

// ============================================================
// TRANSACTIONS — riwayat lengkap per aset
// Alur yang benar:
//   1. User meminjam aset (BORROW, status ACTIVE)
//   2. User mengembalikan → jika kondisi rusak, return_notes berisi
//      "Sedang dalam pengajuan ke Super Admin" dan asset_status_snapshot = PENDING_REVIEW
//   3. Super Admin melihat laporan & mengubah status ke MAINTENANCE (trx tipe MAINTENANCE)
//   4. Setelah selesai diperbaiki, Super Admin menutup trx → status kembali AVAILABLE
// ============================================================
export const transactionsMock = [
  // ── ast001: Laptop Dell Latitude 5520 ─────────────────────
  {
    id: "trx001",
    asset_id: "ast001",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-08-05",
    return_date: "2024-08-15",
    returned_date: "2024-08-14",
    purpose: "Workshop IT eksternal",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kembali lengkap, kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx002",
    asset_id: "ast001",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-09-20",
    return_date: "2024-09-30",
    returned_date: "2024-10-03",
    purpose: "Presentasi ke klien Jakarta",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "Baterai sudah mulai drop.",
    return_notes:
      "Ada goresan pada bodi belakang, baterai terasa tidak optimal. Sedang dalam pengajuan ke Super Admin untuk penanganan lebih lanjut.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx002_maint",
    asset_id: "ast001",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-10-05",
    return_date: "2024-10-20",
    returned_date: "2024-12-08",
    purpose: "Perbaikan goresan bodi & kalibrasi baterai",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx002",
    damage_by: "Denny Kurniawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Denny Kurniawan (trx002). Super Admin mengubah status ke Dalam Perbaikan pada 5 Okt 2024.",
    notes: "Goresan bodi dipoles, baterai diganti sel baru.",
    return_notes: "Bodi dan baterai kembali normal, aset siap digunakan.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx003",
    asset_id: "ast001",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-12-10",
    return_date: "2024-12-20",
    returned_date: "2024-12-19",
    purpose: "Audit lapangan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx004",
    asset_id: "ast001",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-01-15",
    return_date: "2025-01-25",
    returned_date: "2025-01-24",
    purpose: "Training online WFH",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik, charger juga kembali.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast002: Laptop HP EliteBook 840 G8 ───────────────────
  {
    id: "trx005",
    asset_id: "ast002",
    user_id: "u002",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-07-01",
    return_date: "2024-07-10",
    returned_date: "2024-07-09",
    purpose: "Rapat koordinasi cabang",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Normal, tidak ada masalah.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx006",
    asset_id: "ast002",
    user_id: "u005",
    user_name: "Eka Saputra",
    type: "BORROW",
    date: "2024-11-08",
    return_date: "2024-11-18",
    returned_date: "2024-11-20",
    purpose: "Project analisis data",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Terlambat 2 hari, kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx007",
    asset_id: "ast002",
    user_id: "u002",        // Budi Santoso (DUMMY_USERS id:2 → u002)
    user_name: "Budi Santoso",
    type: "BORROW",
    date: _d(-10),          // dipinjam 10 hari lalu
    return_date: _d(1),     // jatuh tempo BESOK → ⚠️ WARNING kuning (H-1)
    returned_date: null,
    purpose: "Presentasi klien di luar kantor",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },
  {
    id: "trx007b",
    asset_id: "ast007",
    user_id: "u002",        // Budi Santoso (DUMMY_USERS id:2 → u002)
    user_name: "Budi Santoso",
    type: "BORROW",
    date: _d(-15),          // dipinjam 15 hari lalu
    return_date: _d(-3),    // jatuh tempo 3 hari lalu → 🚨 OVERDUE merah
    returned_date: null,
    purpose: "Backup laptop rusak",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast003: Desktop PC Lenovo ThinkCentre M720 ───────────
  {
    id: "trx008",
    asset_id: "ast003",
    user_id: "u006",
    user_name: "Fitri Handayani",
    type: "BORROW",
    date: "2024-05-10",
    return_date: "2024-05-25",
    returned_date: "2024-05-24",
    purpose: "Pengganti PC unit rusak",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx009",
    asset_id: "ast003",
    user_id: "u002",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-02-01",
    return_date: "2025-02-15",
    returned_date: "2025-02-14",
    purpose: "Kebutuhan project desain",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Normal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast004: Server Dell PowerEdge R740 ───────────────────
  {
    id: "trx010",
    asset_id: "ast004",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-03-15",
    return_date: "2024-03-25",
    returned_date: "2024-03-26",
    purpose: "Migrasi data server lama",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "Perlu akses khusus ruang server.",
    return_notes:
      "Kabel power salah satu PSU tertekuk saat pemasangan kembali, port PSU2 sedikit longgar. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx011",
    asset_id: "ast004",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-03-28",
    return_date: "2024-04-07",
    returned_date: "2024-04-06",
    purpose: "Perbaikan port PSU2 & penggantian kabel power",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx010",
    damage_by: "Gunawan Setiawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Gunawan Setiawan (trx010). Super Admin mengubah status ke Dalam Perbaikan pada 28 Mar 2024.",
    notes: "Port PSU2 diperbaiki, kabel power diganti baru.",
    return_notes: "Server kembali berfungsi optimal, semua PSU berjalan normal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast005: Switch Cisco Catalyst ───────────────────────
  {
    id: "trx012",
    asset_id: "ast005",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-06-20",
    return_date: "2024-06-30",
    returned_date: "2024-06-29",
    purpose: "Setup jaringan gedung baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Instalasi berhasil, switch kembali normal.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx013",
    asset_id: "ast005",
    user_id: "u008",
    user_name: "Hendra Wijaya",
    type: "BORROW",
    date: "2024-12-02",
    return_date: "2024-12-10",
    returned_date: "2024-12-10",
    purpose: "Troubleshooting jaringan cabang",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Masalah terselesaikan, kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast006: UPS APC Smart-UPS 1500VA ────────────────────
  {
    id: "trx014",
    asset_id: "ast006",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-02-10",
    return_date: "2024-02-20",
    returned_date: "2024-02-20",
    purpose: "Backup power ruang operasional",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Baterai UPS lemah setelah digunakan terus-menerus, runtime turun drastis. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx015",
    asset_id: "ast006",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2026-03-01",
    return_date: "2026-03-20",
    returned_date: null,
    purpose: "Penggantian baterai UPS",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    damage_ref: "trx014",
    damage_by: "Gunawan Setiawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Gunawan Setiawan (trx014). Super Admin mengubah status ke Dalam Perbaikan pada 1 Mar 2026.",
    notes: "Baterai sudah dipesan, menunggu kedatangan dari supplier.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast007: Laptop ASUS ExpertBook B1500 ────────────────
  {
    id: "trx016",
    asset_id: "ast007",
    user_id: "u009",
    user_name: "Indah Permata",
    type: "BORROW",
    date: "2024-04-10",
    return_date: "2024-04-20",
    returned_date: "2024-04-19",
    purpose: "Rekrutmen karyawan baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Baik, lengkap.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx017",
    asset_id: "ast007",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-01-05",
    return_date: "2025-01-12",
    returned_date: "2025-01-11",
    purpose: "Backup laptop utama rusak",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Oke, tidak ada masalah.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast008: Laptop Lenovo ThinkPad X1 Carbon ─────────────
  {
    id: "trx018",
    asset_id: "ast008",
    user_id: "u010",
    user_name: "Joko Santoso",
    type: "BORROW",
    date: "2024-09-01",
    return_date: "2024-09-10",
    returned_date: "2024-09-10",
    purpose: "Rapat direksi luar kota",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "Laptop direktur utama.",
    return_notes: "Kondisi sempurna.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx019",
    asset_id: "ast008",
    user_id: "u010",
    user_name: "Joko Santoso",
    type: "BORROW",
    date: "2026-03-05",
    return_date: "2026-03-20",
    returned_date: null,
    purpose: "Perjalanan dinas ke Jakarta",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast009: Laptop Toshiba Satellite L745 (DELETED) ───────
  {
    id: "trx020",
    asset_id: "ast009",
    user_id: "u011",
    user_name: "Khalid Fadli",
    type: "BORROW",
    date: "2023-03-10",
    return_date: "2023-03-20",
    returned_date: "2023-03-22",
    purpose: "Keperluan training internal",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Layar ada dead pixel di sudut kiri. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx020_maint",
    asset_id: "ast009",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2023-03-25",
    return_date: "2023-04-10",
    returned_date: "2023-04-09",
    purpose: "Investigasi dead pixel layar",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "MINOR_DAMAGE",
    damage_ref: "trx020",
    damage_by: "Khalid Fadli",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Khalid Fadli (trx020). Super Admin mengubah status ke Dalam Perbaikan pada 25 Mar 2023.",
    notes: "Dead pixel tidak dapat diperbaiki tanpa penggantian panel — tidak ekonomis untuk aset tahun 2013.",
    return_notes:
      "Panel tidak diganti. Status kondisi tetap Rusak Ringan. Aset masih bisa digunakan untuk kebutuhan non-kritis.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx021",
    asset_id: "ast009",
    user_id: "u012",
    user_name: "Lina Sari",
    type: "BORROW",
    date: "2023-08-05",
    return_date: "2023-08-15",
    returned_date: "2023-08-16",
    purpose: "Kebutuhan sementara staf baru",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "DAMAGED",
    notes: "Kondisi sudah tidak ideal.",
    return_notes:
      "Charger original hilang, tombol keyboard ada yang lepas. Tidak layak pakai. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx022",
    asset_id: "ast009",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2023-09-01",
    return_date: "2023-09-15",
    returned_date: "2023-09-15",
    purpose: "Evaluasi kelayakan & penghapusan aset tidak layak",
    status: "RETURNED",
    condition_before: "DAMAGED",
    condition_after: "DAMAGED",
    damage_ref: "trx021",
    damage_by: "Lina Sari",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak berat oleh Lina Sari (trx021). Super Admin mengubah status ke Dalam Perbaikan pada 1 Sep 2023 untuk evaluasi kelayakan.",
    notes: "Sudah melalui proses BA penghapusan aset.",
    return_notes:
      "Aset dinyatakan tidak layak operasional. Direkomendasikan dihapus dari inventaris.",
    asset_status_snapshot: "DELETED",
  },

  // ── ast010: Laptop Acer Aspire 5 A515 ────────────────────
  {
    id: "trx023",
    asset_id: "ast010",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-07-10",
    return_date: "2024-07-20",
    returned_date: "2024-07-19",
    purpose: "Kerja lapangan divisi keuangan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kembali dalam kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx024",
    asset_id: "ast010",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-10-05",
    return_date: "2024-10-15",
    returned_date: "2024-10-14",
    purpose: "Presentasi proyek ke manajemen",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Baik, tidak ada kerusakan.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx025",
    asset_id: "ast010",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2026-02-20",
    return_date: "2026-03-01",
    returned_date: "2026-03-02",
    purpose: "Training administrasi keuangan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Terlambat 1 hari. Charger gosong, port USB-A kanan tidak berfungsi setelah laptop terjatuh saat dibawa. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx025_maint",
    asset_id: "ast010",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2026-03-04",
    return_date: "2026-03-25",
    returned_date: null,
    purpose: "Penggantian charger & perbaikan port USB-A",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    damage_ref: "trx025",
    damage_by: "Budi Santoso",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Budi Santoso (trx025). Super Admin mengubah status ke Dalam Perbaikan pada 4 Mar 2026.",
    notes: "Charger baru sudah dipesan, teknisi dijadwalkan 10 Mar 2026.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast011: Laptop MacBook Pro 14 M2 ─────────────────────
  {
    id: "trx026",
    asset_id: "ast011",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-05-12",
    return_date: "2024-05-22",
    returned_date: "2024-05-21",
    purpose: "Setup workstation sementara divisi IT",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Berfungsi normal.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx027",
    asset_id: "ast011",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-09-03",
    return_date: "2024-09-13",
    returned_date: "2024-09-12",
    purpose: "Penggunaan sementara untuk desain presentasi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Tidak ada kendala.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast012: Laptop MSI Modern 14 ──────────────────────────
  {
    id: "trx028",
    asset_id: "ast012",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-06-01",
    return_date: "2024-06-11",
    returned_date: "2024-06-11",
    purpose: "Penggunaan sementara di ruang akuntansi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Layar berkedip saat kecerahan diturunkan, terlihat sejak hari terakhir pemakaian. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx028b",
    asset_id: "ast012",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2026-03-03",
    return_date: "2026-03-17",
    returned_date: null,
    purpose: "Perbaikan layar — flickering & backlight bermasalah",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    damage_ref: "trx028",
    damage_by: "Denny Kurniawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Denny Kurniawan (trx028). Super Admin mengubah status ke Dalam Perbaikan pada 3 Mar 2026.",
    notes:
      "Layar flicker saat brightness rendah, kemungkinan kabel flex longgar. Teknisi sudah dihubungi.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast013: Laptop Dell XPS 13 ────────────────────────────
  {
    id: "trx030",
    asset_id: "ast013",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-04-10",
    return_date: "2024-04-20",
    returned_date: "2024-04-18",
    purpose: "Uji coba software akuntansi baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Berfungsi dengan baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx031",
    asset_id: "ast013",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-11-05",
    return_date: "2024-11-15",
    returned_date: "2024-11-14",
    purpose: "Backup data lapangan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Tidak ada kerusakan.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx029",
    asset_id: "ast013",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-01-08",
    return_date: "2025-01-18",
    returned_date: "2025-01-17",
    purpose: "Penginputan data laporan tahunan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Selesai digunakan, kondisi normal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast014: Laptop HP Pavilion 15 ────────────────────────
  {
    id: "trx032",
    asset_id: "ast014",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-08-20",
    return_date: "2024-08-30",
    returned_date: "2024-08-29",
    purpose: "Rendering desain konstruksi dermaga",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Unit berfungsi optimal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast015: Desktop PC HP ProDesk 400 G7 ─────────────────
  {
    id: "trx033",
    asset_id: "ast015",
    user_id: "u006",
    user_name: "Fitri Handayani",
    type: "BORROW",
    date: "2024-02-10",
    return_date: "2024-02-20",
    returned_date: "2024-02-21",
    purpose: "Penggunaan sementara — PC utama diperbaiki",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Konektor display port longgar setelah sering dipasang-lepas. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx034",
    asset_id: "ast015",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-02-23",
    return_date: "2024-03-05",
    returned_date: "2024-03-04",
    purpose: "Perbaikan konektor display port",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx033",
    damage_by: "Fitri Handayani",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Fitri Handayani (trx033). Super Admin mengubah status ke Dalam Perbaikan pada 23 Feb 2024.",
    notes: "Konektor display port diganti dengan yang baru.",
    return_notes: "Konektor berhasil diganti, output display kembali stabil.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast016: Desktop PC Dell OptiPlex 7090 ────────────────
  {
    id: "trx035",
    asset_id: "ast016",
    user_id: "u008",
    user_name: "Hendra Wijaya",
    type: "BORROW",
    date: "2024-05-15",
    return_date: "2024-05-25",
    returned_date: "2024-05-24",
    purpose: "Keperluan pengolahan data divisi legal",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik, tidak ada masalah.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast017: Desktop PC ASUS Pro E500 G6 ──────────────────
  {
    id: "trx036",
    asset_id: "ast017",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-01-10",
    return_date: "2024-01-20",
    returned_date: "2024-01-22",
    purpose: "Simulasi beban kerja rendering 3D",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "PSU mengeluarkan suara dengingan tidak normal setelah rendering berat terus-menerus. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx036b",
    asset_id: "ast017",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-01-25",
    return_date: "2024-02-05",
    returned_date: "2024-02-04",
    purpose: "Penggantian PSU — dengung akibat beban berlebih",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx036",
    damage_by: "Gunawan Setiawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Gunawan Setiawan (trx036). Super Admin mengubah status ke Dalam Perbaikan pada 25 Jan 2024.",
    notes: "PSU unit menunjukkan tanda-tanda lemah akibat beban berlebih.",
    return_notes: "PSU berhasil diganti, desktop kembali normal dan senyap.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast018: Server HP ProLiant DL380 Gen10 ───────────────
  {
    id: "trx037a",
    asset_id: "ast018",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-04-10",
    return_date: "2024-04-20",
    returned_date: "2024-04-22",
    purpose: "Konfigurasi ulang VLAN & pengujian failover",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "Akses server room diperlukan.",
    return_notes:
      "Salah satu NIC onboard tidak terdeteksi setelah pengkabelan ulang. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx037",
    asset_id: "ast018",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-04-24",
    return_date: "2024-05-04",
    returned_date: "2024-05-03",
    purpose: "Perbaikan NIC onboard & update firmware",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx037a",
    damage_by: "Gunawan Setiawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Gunawan Setiawan (trx037a). Super Admin mengubah status ke Dalam Perbaikan pada 24 Apr 2024.",
    notes: "NIC onboard diperbaiki, firmware diperbarui ke versi terbaru.",
    return_notes:
      "NIC onboard kembali terdeteksi normal, semua layanan jaringan berjalan.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast019: Server IBM System x3650 M5 ───────────────────
  {
    id: "trx038",
    asset_id: "ast019",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-01-05",
    return_date: "2024-01-15",
    returned_date: "2024-01-14",
    purpose: "Pengujian performa server untuk beban data pelabuhan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Server berjalan baik selama pengujian.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx038b",
    asset_id: "ast019",
    user_id: "u008",
    user_name: "Hendra Wijaya",
    type: "BORROW",
    date: "2026-02-20",
    return_date: "2026-03-02",
    returned_date: "2026-03-03",
    purpose: "Migrasi data aplikasi ke server baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "NIC port 2 tidak merespons setelah migrasi selesai, kemungkinan akibat tegangan tidak stabil saat koneksi ulang. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx039",
    asset_id: "ast019",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2026-03-05",
    return_date: "2026-03-15",
    returned_date: null,
    purpose: "Perbaikan NIC port 2 & update BIOS",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    damage_ref: "trx038b",
    damage_by: "Hendra Wijaya",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Hendra Wijaya (trx038b). Super Admin mengubah status ke Dalam Perbaikan pada 5 Mar 2026.",
    notes: "NIC port 2 tidak merespons. Komponen pengganti sedang dipesan.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast020: Router Mikrotik CCR2004 ──────────────────────
  {
    id: "trx040",
    asset_id: "ast020",
    user_id: "u008",
    user_name: "Hendra Wijaya",
    type: "BORROW",
    date: "2024-06-25",
    return_date: "2024-07-05",
    returned_date: "2024-07-04",
    purpose: "Konfigurasi routing gedung baru & update RouterOS",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "RouterOS diperbarui ke versi terbaru, konfigurasi berjalan.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast021: Access Point Ubiquiti UniFi U6 Pro ────────────
  {
    id: "trx041",
    asset_id: "ast021",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-04-15",
    return_date: "2024-04-20",
    returned_date: "2024-04-19",
    purpose: "Pemasangan AP sementara di lobby",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "AP berfungsi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx042",
    asset_id: "ast021",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2026-03-07",
    return_date: "2026-03-20",
    returned_date: null,
    purpose: "Acara pameran pelabuhan — coverage WiFi event",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast022: Firewall Fortinet FortiGate 60F ───────────────
  {
    id: "trx043",
    asset_id: "ast022",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-07-20",
    return_date: "2024-07-30",
    returned_date: "2024-07-29",
    purpose: "Uji coba policy firewall di jaringan simulasi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Perangkat berfungsi normal, tidak ada perubahan konfigurasi.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast023: Switch HP Aruba 2930F 24G ────────────────────
  {
    id: "trx044",
    asset_id: "ast023",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-06-20",
    return_date: "2024-06-30",
    returned_date: "2024-06-28",
    purpose: "Ekspansi jaringan lantai baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Switch berfungsi optimal di lokasi baru.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx045",
    asset_id: "ast023",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2025-01-15",
    return_date: "2025-01-25",
    returned_date: null,
    purpose: "Koneksi jaringan ruang server Basement",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast024: UPS Eaton 5PX 2200VA ─────────────────────────
  {
    id: "trx046",
    asset_id: "ast024",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-09-15",
    return_date: "2024-09-25",
    returned_date: "2024-09-26",
    purpose: "Backup power untuk pengujian infrastruktur",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Runtime UPS berkurang signifikan setelah penggunaan intensif. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx047",
    asset_id: "ast024",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-09-28",
    return_date: "2024-10-08",
    returned_date: "2024-10-07",
    purpose: "Inspeksi & kalibrasi baterai UPS",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx046",
    damage_by: "Gunawan Setiawan",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Gunawan Setiawan (trx046). Super Admin mengubah status ke Dalam Perbaikan pada 28 Sep 2024.",
    notes: "Runtime hanya 5 menit, kalibrasi ulang baterai diperlukan.",
    return_notes: "Baterai dikalibrasi ulang, kapasitas kembali normal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast025: UPS CyberPower PR1500ELCDRT2U ────────────────
  {
    id: "trx048",
    asset_id: "ast025",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-09-01",
    return_date: "2024-09-07",
    returned_date: "2024-09-08",
    purpose: "Backup power untuk demo perangkat jaringan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Terlambat 1 hari. Kabel power UPS terlipat paksa, konektor IEC sedikit bengkok. Tidak bisa dipakai sebelum diperbaiki. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx048b",
    asset_id: "ast025",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-09-10",
    return_date: "2024-09-15",
    returned_date: "2024-09-14",
    purpose: "Penggantian kabel power IEC yang bengkok",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx048",
    damage_by: "Eko Prasetyo",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Eko Prasetyo (trx048). Super Admin mengubah status ke Dalam Perbaikan pada 10 Sep 2024.",
    notes: "Konektor IEC bengkok, kabel diganti dengan yang baru.",
    return_notes:
      "Kabel power berhasil diganti, UPS kembali normal dan siap digunakan.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast026: UPS APC Back-UPS Pro 1200VA ──────────────────
  {
    id: "trx049",
    asset_id: "ast026",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-07-15",
    return_date: "2024-07-25",
    returned_date: "2024-07-24",
    purpose: "Perlindungan perangkat ruang administrasi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik, tidak ada gangguan listrik.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast027: UPS Schneider APC SMT1500I ───────────────────
  {
    id: "trx050a",
    asset_id: "ast027",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-10-10",
    return_date: "2024-10-20",
    returned_date: "2024-10-22",
    purpose: "Backup power ruang server saat pemeliharaan gedung",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Kapasitor mengeluarkan bau hangus setelah penggunaan panjang, performa menurun. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx050",
    asset_id: "ast027",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-10-25",
    return_date: "2024-11-05",
    returned_date: "2024-11-04",
    purpose: "Penggantian kapasitor UPS",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx050a",
    damage_by: "Eko Prasetyo",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Eko Prasetyo (trx050a). Super Admin mengubah status ke Dalam Perbaikan pada 25 Okt 2024.",
    notes: "Kapasitor menunjukkan tanda penuaan akibat beban berlebih.",
    return_notes: "Kapasitor berhasil diganti, UPS kembali optimal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast028: Printer HP LaserJet Pro M404n ────────────────
  {
    id: "trx051",
    asset_id: "ast028",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-05-10",
    return_date: "2024-05-20",
    returned_date: "2024-05-18",
    purpose: "Cetak dokumen tender pelabuhan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Printer berfungsi baik, toner masih 60%.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx052",
    asset_id: "ast028",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-12-01",
    return_date: "2024-12-07",
    returned_date: "2024-12-06",
    purpose: "Cetak laporan audit akhir tahun",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Selesai cetak, kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast029: Monitor LG UltraWide 34WN80C ─────────────────
  {
    id: "trx053",
    asset_id: "ast029",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-06-15",
    return_date: "2024-06-25",
    returned_date: "2024-06-24",
    purpose: "Presentasi desain pelabuhan ke direksi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Monitor baik, tidak ada dead pixel.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx054",
    asset_id: "ast029",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2026-02-15",
    return_date: "2026-02-25",
    returned_date: "2026-02-25",
    purpose: "Review dokumen pelelangan aset",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Sudut bawah panel layar retak saat monitor tidak sengaja tersenggol meja. Masih menyala tapi ada garis vertikal di area retak. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx054_maint",
    asset_id: "ast029",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2026-02-27",
    return_date: "2026-03-25",
    returned_date: null,
    purpose: "Penggantian panel layar — retak akibat benturan",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    damage_ref: "trx054",
    damage_by: "Budi Santoso",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Budi Santoso (trx054). Super Admin mengubah status ke Dalam Perbaikan pada 27 Feb 2026.",
    notes: "Panel pengganti sudah dipesan dari supplier, estimasi tiba 15 Mar.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast030: Proyektor Epson EB-X51 ───────────────────────
  {
    id: "trx055",
    asset_id: "ast030",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-08-01",
    return_date: "2024-08-03",
    returned_date: "2024-08-03",
    purpose: "Presentasi bulanan manajemen",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Berfungsi baik, kabel lengkap.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx056",
    asset_id: "ast030",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-11-10",
    return_date: "2024-11-12",
    returned_date: "2024-11-12",
    purpose: "Seminar K3 pelabuhan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Proyektor baik, lampu masih terang.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx057",
    asset_id: "ast030",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2025-02-15",
    return_date: "2025-02-17",
    returned_date: null,
    purpose: "Pelatihan operator terminal baru",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast031: Proyektor BenQ MH550 ─────────────────────────
  {
    id: "trx058",
    asset_id: "ast031",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-07-22",
    return_date: "2024-07-24",
    returned_date: "2024-07-24",
    purpose: "Rapat evaluasi kinerja semester",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Baik, semua aksesori lengkap.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx059",
    asset_id: "ast031",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-01-05",
    return_date: "2025-01-07",
    returned_date: "2025-01-07",
    purpose: "Kick-off proyek digitalisasi pelabuhan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi sangat baik.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast032: Scanner Fujitsu fi-7160 ──────────────────────
  {
    id: "trx060",
    asset_id: "ast032",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-09-15",
    return_date: "2024-09-25",
    returned_date: "2024-09-24",
    purpose: "Digitalisasi arsip dokumen kepelabuhanan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Scanner berfungsi optimal, tidak ada paper jam.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast033: Kamera CCTV Hikvision DS-2CD2143G2 ────────────
  {
    id: "trx061",
    asset_id: "ast033",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-05-01",
    return_date: "2024-05-10",
    returned_date: "2024-05-09",
    purpose: "Pemasangan CCTV sementara area gudang",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Unit berfungsi baik selama pemasangan.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx062",
    asset_id: "ast033",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2026-03-01",
    return_date: "2026-03-31",
    returned_date: null,
    purpose: "Monitoring area dermaga selama perbaikan",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast034: NVR Dahua DHI-NVR4116HS-4KS2 ────────────────
  {
    id: "trx063a",
    asset_id: "ast034",
    user_id: "u005",
    user_name: "Eko Prasetyo",
    type: "BORROW",
    date: "2024-09-10",
    return_date: "2024-09-20",
    returned_date: "2024-09-22",
    purpose: "Pengujian integrasi NVR dengan kamera baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes:
      "Salah satu slot HDD tidak terbaca setelah pemasangan HDD eksternal. Sedang dalam pengajuan ke Super Admin untuk penanganan.",
    asset_status_snapshot: "PENDING_REVIEW",
  },
  {
    id: "trx063",
    asset_id: "ast034",
    user_id: "admin",
    user_name: "Ahmad Fauzi",
    type: "MAINTENANCE",
    maintenance_type: "DAMAGE",
    date: "2024-09-24",
    return_date: "2024-10-04",
    returned_date: "2024-10-03",
    purpose: "Perbaikan slot HDD & konfigurasi ulang NVR",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    damage_ref: "trx063a",
    damage_by: "Eko Prasetyo",
    admin_reason:
      "Aset dikembalikan dalam kondisi rusak ringan oleh Eko Prasetyo (trx063a). Super Admin mengubah status ke Dalam Perbaikan pada 24 Sep 2024.",
    notes: "Slot HDD dibersihkan dan dikalibrasi ulang.",
    return_notes: "8 channel terkonfigurasi ulang, recording normal.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast035: Telepon VOIP Grandstream GXP2160 ─────────────
  {
    id: "trx064",
    asset_id: "ast035",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-06-05",
    return_date: "2024-06-15",
    returned_date: "2024-06-14",
    purpose: "Uji coba telepon VOIP di ruang direksi",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Telepon berfungsi baik, suara jernih.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx065",
    asset_id: "ast035",
    user_id: "u001",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-12-15",
    return_date: "2024-12-20",
    returned_date: "2024-12-19",
    purpose: "Konferensi VOIP akhir tahun",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Berfungsi baik, tidak ada gangguan.",
    asset_status_snapshot: "AVAILABLE",
  },
];

// ---- Users (for reference in history display) ----
export const usersMock = [
  { id: "u001", name: "Budi Santoso", role: "user", avatar: null },
  { id: "u002", name: "Budi Santoso", role: "user", avatar: null },
  { id: "u003", name: "Citra Dewi", role: "user", avatar: null },
  { id: "u004", name: "Denny Kurniawan", role: "user", avatar: null },
  { id: "u005", name: "Eko Prasetyo", role: "user", avatar: null },
  { id: "u006", name: "Fitri Handayani", role: "user", avatar: null },
  { id: "u007", name: "Gunawan Setiawan", role: "user", avatar: null },
  { id: "u008", name: "Hendra Wijaya", role: "user", avatar: null },
  { id: "u009", name: "Indah Permata", role: "user", avatar: null },
  { id: "u010", name: "Joko Santoso", role: "user", avatar: null },
  { id: "u011", name: "Khalid Fadli", role: "user", avatar: null },
  { id: "u012", name: "Lina Sari", role: "user", avatar: null },
  { id: "admin", name: "Ahmad Fauzi", role: "superadmin", avatar: null },
];

export const roleConf = {
  user: { label: "User", color: "#2563eb", bg: "#dbeafe" },
  superadmin: { label: "Super Admin", color: "#7c3aed", bg: "#f5f3ff" },
};

// maintenance_type: untuk menjelaskan konteks di riwayat modal
// DAMAGE  = aset rusak saat dipinjam → user melaporkan → Super Admin tindak lanjuti
// ROUTINE = perawatan rutin / preventive maintenance
export const maintenanceTypeConf = {
  DAMAGE: {
    label: "Rusak saat dipinjam",
    color: "#dc2626",
    bg: "#fee2e2",
    icon: "damage",
  },
  ROUTINE: {
    label: "Perawatan rutin",
    color: "#059669",
    bg: "#dcfce7",
    icon: "routine",
  },
};

// ---- Configs ----
export const categoryConf = {
  LAPTOP: { label: "Laptop", color: "#2563eb", bg: "#eff6ff" },
  SERVER: { label: "Server", color: "#7c3aed", bg: "#f5f3ff" },
  DESKTOP: { label: "Desktop", color: "#0891b2", bg: "#ecfeff" },
  NETWORK: { label: "Network", color: "#059669", bg: "#ecfdf5" },
  UPS: { label: "UPS", color: "#d97706", bg: "#fffbeb" },
  OTHER: { label: "Lainnya", color: "#64748b", bg: "#f8fafc" },
};

export const statusConf = {
  AVAILABLE: {
    label: "Tersedia",
    color: "#16a34a",
    bg: "#dcfce7",
    dot: "#22c55e",
  },
  BORROWED: {
    label: "Dipinjam",
    color: "#d97706",
    bg: "#fef9c3",
    dot: "#f59e0b",
  },
  MAINTENANCE: {
    label: "Dalam Perbaikan",
    color: "#dc2626",
    bg: "#fee2e2",
    dot: "#ef4444",
  },
  PENDING_REVIEW: {
    label: "Pengajuan ke Admin",
    color: "#7c3aed",
    bg: "#f5f3ff",
    dot: "#8b5cf6",
  },
  DELETED: {
    label: "Dihapus",
    color: "#64748b",
    bg: "#f1f5f9",
    dot: "#94a3b8",
  },
};

export const conditionConf = {
  GOOD: { label: "Baik", color: "#16a34a", bg: "#dcfce7" },
  MINOR_DAMAGE: { label: "Rusak Ringan", color: "#d97706", bg: "#fef9c3" },
  DAMAGED: { label: "Rusak Berat", color: "#dc2626", bg: "#fee2e2" },
};

export const trxTypeConf = {
  BORROW: { label: "Peminjaman", color: "#2563eb", bg: "#dbeafe" },
  MAINTENANCE: { label: "Perbaikan", color: "#dc2626", bg: "#fee2e2" },
};

// ---- Formatters ----
export const fmtIDR = (n) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(n);

export const fmt = (d) => {
  if (!d) return "-";
  const [y, m, day] = d.split("-");
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Mei",
    "Jun",
    "Jul",
    "Agu",
    "Sep",
    "Okt",
    "Nov",
    "Des",
  ];
  return `${parseInt(day, 10)} ${months[parseInt(m, 10) - 1]} ${y}`;
};

export const isOverdue = (dateStr) => {
  if (!dateStr) return false;
  return new Date(dateStr) < new Date();
};