// ============================================================
// data.js — Mock data & shared helpers for User Interface
// ============================================================

export const currentUser = {
  id: "u001",
  name: "Andi Pratama",
  nip: "198501012010011001",
  username: "andi.pratama",
  email: "andi.pratama@perusahaan.co.id",
  phone: "081234567890",
  role_code: "user",
  entity_code: "ENT001",
  entity_name: "PT Maju Bersama",
  branch_code: "SBY",
  branch_name: "Cabang Surabaya",
  avatar: null,
};

export const assetsMock = [
  // ── LAPTOP ─────────────────────────────────────────────────
  {
    id: "ast001",
    name: "Laptop Dell Latitude 5520",
    category: "LAPTOP",
    brand: "Dell",
    model: "Latitude 5520",
    serial: "SN-DL-001234",
    location: "Ruang IT - Lantai 3",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 18500000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i5-1135G7",
      ram: "16 GB DDR4",
      storage: "512 GB SSD NVMe",
      display: '15.6" FHD IPS',
      os: "Windows 11 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 63Wh",
      weight: "1.76 kg",
    },
  },
  {
    id: "ast002",
    name: "Laptop HP EliteBook 840 G8",
    category: "LAPTOP",
    brand: "HP",
    model: "EliteBook 840 G8",
    serial: "SN-HP-005678",
    location: "Ruang IT - Lantai 3",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 16750000,
    budget_type: "OPEX",
    spec: {
      cpu: "Intel Core i7-1165G7",
      ram: "16 GB DDR4",
      storage: "256 GB SSD",
      display: '14" FHD IPS',
      os: "Windows 10 Pro",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 53Wh",
      weight: "1.46 kg",
    },
  },
  {
    id: "ast007",
    name: "Laptop ASUS ExpertBook B1500",
    category: "LAPTOP",
    brand: "ASUS",
    model: "ExpertBook B1500",
    serial: "SN-AS-011234",
    location: "Ruang HR - Lantai 2",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 14200000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i5-1235U",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "2-Cell 42Wh",
      weight: "1.8 kg",
    },
  },
  {
    id: "ast008",
    name: "Laptop Lenovo ThinkPad X1 Carbon",
    category: "LAPTOP",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 9",
    serial: "SN-LN-015678",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 24500000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i7-1165G7",
      ram: "16 GB LPDDR4x",
      storage: "1 TB SSD NVMe",
      display: '14" 2K IPS',
      os: "Windows 10 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 57Wh",
      weight: "1.13 kg",
    },
  },
  {
    id: "ast009",
    name: "Laptop Toshiba Satellite L745",
    category: "LAPTOP",
    brand: "Toshiba",
    model: "Satellite L745",
    serial: "SN-TS-099001",
    location: "Gudang - Lantai 1",
    branch_code: "SBY",
    status: "DELETED",
    condition: "DAMAGED",
    year: 2013,
    price: 4500000,
    budget_type: "OPEX",
    spec: {
      cpu: "Intel Core i3-2330M",
      ram: "4 GB DDR3",
      storage: "500 GB HDD",
      display: '14" HD',
      os: "Windows 7 (EOL)",
      gpu: "Intel HD 3000",
    },
  },
  {
    id: "ast010",
    name: "Laptop Acer Aspire 5 A515",
    category: "LAPTOP",
    brand: "Acer",
    model: "Aspire 5 A515-56",
    serial: "SN-AC-022345",
    location: "Ruang Marketing - Lantai 2",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 9800000,
    budget_type: "OPEX",
    spec: {
      cpu: "Intel Core i5-1135G7",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 48Wh",
      weight: "1.9 kg",
    },
  },
  {
    id: "ast011",
    name: "Laptop MacBook Pro 14 M2",
    category: "LAPTOP",
    brand: "Apple",
    model: "MacBook Pro 14-inch M2",
    serial: "SN-AP-033456",
    location: "Ruang Desain - Lantai 3",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 32000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Apple M2 Pro 10-core",
      ram: "16 GB Unified",
      storage: "512 GB SSD",
      display: '14.2" Liquid Retina XDR',
      os: "macOS Ventura",
      gpu: "Apple M2 Pro 16-core GPU",
      battery: "70Wh",
      weight: "1.6 kg",
    },
  },
  {
    id: "ast012",
    name: "Laptop MSI Modern 14",
    category: "LAPTOP",
    brand: "MSI",
    model: "Modern 14 B11SBU",
    serial: "SN-MS-044567",
    location: "Ruang Finance - Lantai 2",
    branch_code: "SBY",
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2021,
    price: 11500000,
    budget_type: "OPEX",
    spec: {
      cpu: "Intel Core i5-1155G7",
      ram: "8 GB DDR4",
      storage: "512 GB NVMe SSD",
      display: '14" FHD IPS',
      os: "Windows 11 Home",
      gpu: "NVIDIA GeForce MX450",
      battery: "3-Cell 52Wh",
      weight: "1.4 kg",
    },
  },
  {
    id: "ast013",
    name: "Laptop Dell XPS 13",
    category: "LAPTOP",
    brand: "Dell",
    model: "XPS 13 9310",
    serial: "SN-DL-055678",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 22000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i7-1185G7",
      ram: "16 GB LPDDR4x",
      storage: "512 GB SSD",
      display: '13.4" FHD+ Touch',
      os: "Windows 11 Pro",
      gpu: "Intel Iris Xe",
      battery: "4-Cell 52Wh",
      weight: "1.2 kg",
    },
  },
  {
    id: "ast014",
    name: "Laptop HP Pavilion 15",
    category: "LAPTOP",
    brand: "HP",
    model: "Pavilion 15-eg2000",
    serial: "SN-HP-066789",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2022,
    price: 10500000,
    budget_type: "OPEX",
    spec: {
      cpu: "Intel Core i5-1235U",
      ram: "8 GB DDR4",
      storage: "512 GB SSD",
      display: '15.6" FHD IPS',
      os: "Windows 11 Home",
      gpu: "Intel Iris Xe",
      battery: "3-Cell 41Wh",
      weight: "1.75 kg",
    },
  },

  // ── DESKTOP ────────────────────────────────────────────────
  {
    id: "ast003",
    name: "Desktop PC Lenovo ThinkCentre M720",
    category: "DESKTOP",
    brand: "Lenovo",
    model: "ThinkCentre M720",
    serial: "SN-LN-009012",
    location: "Ruang Operasional - Lantai 2",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 12000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i5-9400",
      ram: "8 GB DDR4",
      storage: "1 TB HDD + 256 GB SSD",
      display: "N/A (Desktop)",
      os: "Windows 10 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.1, HDMI, DP",
      form: "Tower",
    },
  },
  {
    id: "ast015",
    name: "Desktop PC HP ProDesk 400 G7",
    category: "DESKTOP",
    brand: "HP",
    model: "ProDesk 400 G7",
    serial: "SN-HP-077890",
    location: "Ruang Akuntansi - Lantai 2",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 10800000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i5-10500",
      ram: "8 GB DDR4",
      storage: "256 GB SSD",
      os: "Windows 10 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.2, HDMI, DP",
      form: "Micro Tower",
    },
  },
  {
    id: "ast016",
    name: "Desktop PC Dell OptiPlex 7090",
    category: "DESKTOP",
    brand: "Dell",
    model: "OptiPlex 7090",
    serial: "SN-DL-088901",
    location: "Ruang Legal - Lantai 3",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 13500000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i7-10700",
      ram: "16 GB DDR4",
      storage: "512 GB SSD",
      os: "Windows 11 Pro",
      gpu: "Intel UHD 630",
      ports: "USB 3.2, HDMI, DP, TB4",
      form: "Small Form Factor",
    },
  },
  {
    id: "ast017",
    name: "Desktop PC ASUS Pro E500 G6",
    category: "DESKTOP",
    brand: "ASUS",
    model: "Pro E500 G6",
    serial: "SN-AS-099012",
    location: "Ruang Engineering - Lantai 3",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2021,
    price: 15200000,
    budget_type: "CAPEX",
    spec: {
      cpu: "Intel Core i9-10900",
      ram: "32 GB DDR4",
      storage: "1 TB SSD NVMe",
      os: "Windows 10 Pro",
      gpu: "NVIDIA Quadro P620",
      ports: "USB 3.2, HDMI, DP",
      form: "Tower",
    },
  },

  // ── SERVER ─────────────────────────────────────────────────
  {
    id: "ast004",
    name: "Server Dell PowerEdge R740",
    category: "SERVER",
    brand: "Dell",
    model: "PowerEdge R740",
    serial: "SN-SV-000001",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 185000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "2x Intel Xeon Gold 6226R",
      ram: "256 GB DDR4 ECC",
      storage: "8x 2TB SAS RAID",
      os: "Ubuntu Server 22.04",
      network: "4x 1GbE + 2x 10GbE",
      power: "Dual 750W PSU",
      rack: "2U Rack Mount",
      mgmt: "iDRAC9",
    },
  },
  {
    id: "ast018",
    name: "Server HP ProLiant DL380 Gen10",
    category: "SERVER",
    brand: "HP",
    model: "ProLiant DL380 Gen10",
    serial: "SN-SV-000002",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 210000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "2x Intel Xeon Silver 4210R",
      ram: "128 GB DDR4 ECC",
      storage: "4x 1.92TB SSD RAID",
      os: "VMware ESXi 7.0",
      network: "4x 1GbE FlexibleLOM",
      power: "Dual 800W PSU",
      rack: "2U Rack",
      mgmt: "iLO5",
    },
  },
  {
    id: "ast019",
    name: "Server IBM System x3650 M5",
    category: "SERVER",
    brand: "IBM",
    model: "System x3650 M5",
    serial: "SN-SV-000003",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2018,
    price: 145000000,
    budget_type: "CAPEX",
    spec: {
      cpu: "2x Intel Xeon E5-2620 v4",
      ram: "64 GB DDR4 ECC",
      storage: "6x 600GB SAS HDD",
      os: "Red Hat Enterprise Linux 8",
      network: "4x 1GbE",
      power: "Dual 900W PSU",
      rack: "2U Rack",
      mgmt: "IMM2",
    },
  },

  // ── NETWORK ────────────────────────────────────────────────
  {
    id: "ast005",
    name: "Switch Cisco Catalyst 2960X-48",
    category: "NETWORK",
    brand: "Cisco",
    model: "Catalyst 2960X-48",
    serial: "SN-NW-002345",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2019,
    price: 25000000,
    budget_type: "CAPEX",
    spec: {
      ports: "48x GbE + 4x SFP+",
      throughput: "176 Gbps",
      poe: "Yes, 740W PoE+",
      vlan: "Up to 4094 VLANs",
      mgmt: "Web, CLI, SNMP",
      rack: "1U Rack",
      memory: "256 MB DRAM",
      flash: "128 MB Flash",
    },
  },
  {
    id: "ast020",
    name: "Router Mikrotik CCR2004",
    category: "NETWORK",
    brand: "Mikrotik",
    model: "CCR2004-1G-12S+2XS",
    serial: "SN-NW-013456",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 18500000,
    budget_type: "CAPEX",
    spec: {
      ports: "12x SFP+ + 2x 25G SFP28",
      cpu: "4-core ARM Cortex-A72",
      ram: "4 GB DDR4",
      throughput: "Up to 100 Gbps",
      mgmt: "WinBox, WebFig, SSH",
      rack: "1U Rack",
      os: "RouterOS v7",
    },
  },
  {
    id: "ast021",
    name: "Access Point Ubiquiti UniFi U6 Pro",
    category: "NETWORK",
    brand: "Ubiquiti",
    model: "UniFi U6 Pro",
    serial: "SN-NW-024567",
    location: "Lobby - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 4200000,
    budget_type: "OPEX",
    spec: {
      wifi: "WiFi 6 (802.11ax)",
      bands: "2.4 GHz + 5 GHz",
      speed: "Up to 4.8 Gbps",
      antennas: "6 antennas",
      poe: "802.3at PoE",
      coverage: "~185 m²",
      concurrent: "300+ clients",
    },
  },
  {
    id: "ast022",
    name: "Firewall Fortinet FortiGate 60F",
    category: "NETWORK",
    brand: "Fortinet",
    model: "FortiGate 60F",
    serial: "SN-NW-035678",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 32000000,
    budget_type: "CAPEX",
    spec: {
      throughput: "10 Gbps Firewall",
      vpn: "6.5 Gbps IPsec VPN",
      ports: "10x GbE",
      storage: "128 GB SSD",
      mgmt: "FortiOS, FortiManager",
      rack: "Desktop/1U",
    },
  },
  {
    id: "ast023",
    name: "Switch HP Aruba 2930F 24G",
    category: "NETWORK",
    brand: "HP",
    model: "Aruba 2930F 24G",
    serial: "SN-NW-046789",
    location: "Ruang Server - Basement",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2020,
    price: 14800000,
    budget_type: "CAPEX",
    spec: {
      ports: "24x GbE + 4x SFP+",
      throughput: "128 Gbps",
      poe: "Yes, PoE+",
      vlan: "4094 VLANs",
      mgmt: "Web, CLI, SNMP",
      rack: "1U Rack",
      memory: "512 MB",
    },
  },

  // ── UPS ─────────────────────────────────────────────────────
  {
    id: "ast006",
    name: "UPS APC Smart-UPS 1500VA",
    category: "UPS",
    brand: "APC",
    model: "Smart-UPS 1500VA",
    serial: "SN-UP-007890",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "MAINTENANCE",
    condition: "MINOR_DAMAGE",
    year: 2018,
    price: 8500000,
    budget_type: "OPEX",
    spec: {
      capacity: "1500VA / 1000W",
      runtime: "~14 min at full load",
      input: "220-230V AC",
      output: "220-230V AC",
      battery: "24V Lead Acid",
      interface: "USB, Serial",
      mgmt: "APC PowerChute",
      form: "Tower/Rack",
    },
  },
  {
    id: "ast024",
    name: "UPS Eaton 5PX 2200VA",
    category: "UPS",
    brand: "Eaton",
    model: "5PX 2200VA RT2U",
    serial: "SN-UP-018901",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 14500000,
    budget_type: "CAPEX",
    spec: {
      capacity: "2200VA / 1980W",
      runtime: "~10 min at full load",
      input: "200-240V AC",
      output: "200-240V AC",
      battery: "Lithium-ion",
      interface: "USB, RS-232, Network Card",
      mgmt: "Eaton Intelligent Power Manager",
      form: "2U Rack",
    },
  },
  {
    id: "ast025",
    name: "UPS CyberPower PR1500ELCDRT2U",
    category: "UPS",
    brand: "CyberPower",
    model: "PR1500ELCDRT2U",
    serial: "SN-UP-029012",
    location: "Ruang Network - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 9800000,
    budget_type: "OPEX",
    spec: {
      capacity: "1500VA / 1350W",
      runtime: "~12 min at full load",
      input: "200-240V AC",
      output: "200-240V AC",
      battery: "12V 9Ah x2",
      interface: "USB, RS-232",
      mgmt: "PowerPanel Business",
      form: "2U Rack",
    },
  },
  {
    id: "ast026",
    name: "UPS APC Back-UPS Pro 1200VA",
    category: "UPS",
    brand: "APC",
    model: "Back-UPS Pro BR1200GI",
    serial: "SN-UP-030123",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 5200000,
    budget_type: "OPEX",
    spec: {
      capacity: "1200VA / 720W",
      runtime: "~20 min at half load",
      input: "220-230V AC",
      output: "220-230V AC",
      battery: "12V Lead Acid",
      interface: "USB",
      mgmt: "APC PowerChute Personal",
      form: "Tower",
    },
  },
  {
    id: "ast027",
    name: "UPS Schneider APC SMT1500I",
    category: "UPS",
    brand: "Schneider",
    model: "APC SMT1500I",
    serial: "SN-UP-041234",
    location: "Server Room - Basement",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2020,
    price: 11200000,
    budget_type: "CAPEX",
    spec: {
      capacity: "1500VA / 1000W",
      runtime: "~16 min at full load",
      input: "230V AC",
      output: "230V AC",
      battery: "24V Lead Acid",
      interface: "USB, SmartSlot",
      mgmt: "PowerChute Network Shutdown",
      form: "Tower/Rack",
    },
  },

  // ── OTHER ────────────────────────────────────────────────────
  {
    id: "ast028",
    name: "Printer HP LaserJet Pro M404n",
    category: "OTHER",
    brand: "HP",
    model: "LaserJet Pro M404n",
    serial: "SN-OT-052345",
    location: "Ruang Administrasi - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 4800000,
    budget_type: "OPEX",
    spec: {
      type: "Laser Monochrome",
      speed: "40 ppm",
      resolution: "1200 x 1200 dpi",
      paper: "A4, Letter, Legal",
      connect: "USB, LAN",
      memory: "256 MB",
      duty: "80,000 pages/month",
    },
  },
  {
    id: "ast029",
    name: "Monitor LG UltraWide 34WN80C",
    category: "OTHER",
    brand: "LG",
    model: "34WN80C-B",
    serial: "SN-OT-063456",
    location: "Ruang Desain - Lantai 3",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 8500000,
    budget_type: "CAPEX",
    spec: {
      size: '34" Curved IPS',
      resolution: "3440 x 1440 (UWQHD)",
      refresh: "60 Hz",
      response: "5ms",
      hdr: "HDR10",
      connect: "HDMI, USB-C, USB Hub",
      brightness: "300 cd/m²",
    },
  },
  {
    id: "ast030",
    name: "Proyektor Epson EB-X51",
    category: "OTHER",
    brand: "Epson",
    model: "EB-X51",
    serial: "SN-OT-074567",
    location: "Ruang Rapat A - Lantai 2",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 6200000,
    budget_type: "OPEX",
    spec: {
      brightness: "3800 lumens",
      resolution: "XGA (1024 x 768)",
      ratio: "4:3",
      lamp: "200W",
      lamp_life: "10,000 hours (ECO)",
      connect: "HDMI, VGA, USB",
      throw: "1.48-1.78:1",
    },
  },
  {
    id: "ast031",
    name: "Proyektor Benq MH550",
    category: "OTHER",
    brand: "Benq",
    model: "MH550",
    serial: "SN-OT-085678",
    location: "Ruang Rapat B - Lantai 3",
    branch_code: "SBY",
    status: "BORROWED",
    condition: "GOOD",
    year: 2022,
    price: 5800000,
    budget_type: "OPEX",
    spec: {
      brightness: "3500 lumens",
      resolution: "Full HD (1920 x 1080)",
      ratio: "16:9",
      lamp: "240W",
      lamp_life: "8,000 hours (SmartEco)",
      connect: "HDMI, VGA, USB",
      throw: "1.47-1.76:1",
    },
  },
  {
    id: "ast032",
    name: "Scanner Fujitsu fi-7160",
    category: "OTHER",
    brand: "Fujitsu",
    model: "fi-7160",
    serial: "SN-OT-096789",
    location: "Ruang Arsip - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2020,
    price: 12500000,
    budget_type: "CAPEX",
    spec: {
      speed: "60 ppm / 120 ipm",
      resolution: "600 dpi optical",
      adf: "80-sheet ADF",
      paper: "A8 - A3",
      connect: "USB 3.0",
      os: "Windows, Mac",
      weight: "2.6 kg",
    },
  },
  {
    id: "ast033",
    name: "Kamera CCTV Hikvision DS-2CD2143G2",
    category: "OTHER",
    brand: "Hikvision",
    model: "DS-2CD2143G2-I",
    serial: "SN-OT-107890",
    location: "Lobby - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2023,
    price: 1800000,
    budget_type: "OPEX",
    spec: {
      resolution: "4 MP",
      lens: "2.8mm",
      ir: "60m IR range",
      ip: "IP67 weatherproof",
      h265: "H.265+",
      poe: "PoE (802.3af)",
      features: "AcuSense, Wide Angle",
    },
  },
  {
    id: "ast034",
    name: "NVR Dahua DHI-NVR4116HS-4KS2",
    category: "OTHER",
    brand: "Dahua",
    model: "DHI-NVR4116HS-4KS2",
    serial: "SN-OT-118901",
    location: "Ruang Security - Lantai 1",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2022,
    price: 3200000,
    budget_type: "OPEX",
    spec: {
      channels: "16 IP channels",
      resolution: "Up to 8MP",
      playback: "4-channel 4K",
      hdd: "Up to 8TB",
      network: "2x RJ-45 1GbE",
      connect: "2x USB, 1x HDMI, 1x VGA",
      compression: "H.265+",
    },
  },
  {
    id: "ast035",
    name: "Telepon VOIP Grandstream GXP2160",
    category: "OTHER",
    brand: "Grandstream",
    model: "GXP2160",
    serial: "SN-OT-129012",
    location: "Ruang Direksi - Lantai 4",
    branch_code: "SBY",
    status: "AVAILABLE",
    condition: "GOOD",
    year: 2021,
    price: 2800000,
    budget_type: "OPEX",
    spec: {
      lines: "6 SIP lines",
      keys: "24 programmable BLF keys",
      display: '4.3" Color LCD',
      audio: "HD Audio, Full-duplex",
      connect: "2x GbE, USB",
      poe: "PoE (802.3af)",
      codecs: "G.722, G.711, G.729",
    },
  },
];

// ============================================================
// TRANSACTIONS — riwayat lengkap per aset
// ============================================================
export const transactionsMock = [
  // ── ast001: Laptop Dell Latitude 5520 ─────────────────────
  {
    id: "trx001",
    asset_id: "ast001",
    user_id: "u003",
    user_name: "Citra Dewi",
    type: "BORROW",
    date: "2024-08-05",
    return_date: "2024-08-15",
    returned_date: "2024-08-14",
    purpose: "Workshop IT eksternal",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kembali lengkap, kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx002",
    asset_id: "ast001",
    user_id: "u004",
    user_name: "Denny Kurniawan",
    type: "BORROW",
    date: "2024-09-20",
    return_date: "2024-09-30",
    returned_date: "2024-10-03",
    purpose: "Presentasi ke klien Jakarta",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "Baterai sudah mulai drop.",
    return_notes:
      "Ada goresan pada bodi belakang, baterai dirasa kurang optimal.",
    asset_status_snapshot: "BORROWED",
  },
  {
    id: "trx003",
    asset_id: "ast001",
    user_id: "u001",
    user_name: "Andi Pratama",
    type: "BORROW",
    date: "2024-12-10",
    return_date: "2024-12-20",
    returned_date: "2024-12-19",
    purpose: "Audit lapangan",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "GOOD",
    notes: "Sudah diperbaiki sebelum dipinjam.",
    return_notes: "Kondisi baik setelah service.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx004",
    asset_id: "ast001",
    user_id: "u001",
    user_name: "Andi Pratama",
    type: "BORROW",
    date: "2025-01-15",
    return_date: "2025-01-25",
    returned_date: "2025-01-24",
    purpose: "Training online WFH",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik, charger juga kembali.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast002: Laptop HP EliteBook 840 G8 ───────────────────
  {
    id: "trx005",
    asset_id: "ast002",
    user_id: "u002",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2024-07-01",
    return_date: "2024-07-10",
    returned_date: "2024-07-09",
    purpose: "Rapat koordinasi cabang",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Normal, tidak ada masalah.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx006",
    asset_id: "ast002",
    user_id: "u005",
    user_name: "Eka Saputra",
    type: "BORROW",
    date: "2024-11-08",
    return_date: "2024-11-18",
    returned_date: "2024-11-20",
    purpose: "Project analisis data",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Terlambat 2 hari, kondisi baik.",
    asset_status_snapshot: "BORROWED",
  },
  {
    id: "trx007",
    asset_id: "ast002",
    user_id: "u001",
    user_name: "Andi Pratama",
    type: "BORROW",
    date: "2025-02-10",
    return_date: "2025-02-20",
    returned_date: null,
    purpose: "Presentasi klien di luar kantor",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast003: Desktop PC Lenovo ThinkCentre M720 ───────────
  {
    id: "trx008",
    asset_id: "ast003",
    user_id: "u006",
    user_name: "Fitri Handayani",
    type: "BORROW",
    date: "2024-05-10",
    return_date: "2024-05-25",
    returned_date: "2024-05-24",
    purpose: "Pengganti PC unit rusak",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Kondisi baik.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx009",
    asset_id: "ast003",
    user_id: "u002",
    user_name: "Budi Santoso",
    type: "BORROW",
    date: "2025-02-01",
    return_date: "2025-02-15",
    returned_date: "2025-02-14",
    purpose: "Kebutuhan project desain",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Normal.",
    asset_status_snapshot: "BORROWED",
  },

  // ── ast004: Server Dell PowerEdge R740 ───────────────────
  {
    id: "trx010",
    asset_id: "ast004",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-03-15",
    return_date: "2024-03-25",
    returned_date: "2024-03-25",
    purpose: "Migrasi data server lama",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "Perlu akses khusus ruang server.",
    return_notes: "Selesai, semua data berhasil dipindahkan.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx011",
    asset_id: "ast004",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "MAINTENANCE",
    date: "2024-10-01",
    return_date: "2024-10-07",
    returned_date: "2024-10-06",
    purpose: "Preventive maintenance tahunan",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "Ganti thermal paste, bersihkan debu.",
    return_notes: "Sudah selesai maintenance, performa optimal.",
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast005: Switch Cisco Catalyst ───────────────────────
  {
    id: "trx012",
    asset_id: "ast005",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-06-20",
    return_date: "2024-06-30",
    returned_date: "2024-06-29",
    purpose: "Setup jaringan gedung baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Instalasi berhasil, switch kembali normal.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx013",
    asset_id: "ast005",
    user_id: "u008",
    user_name: "Hendra Wijaya",
    type: "BORROW",
    date: "2024-12-02",
    return_date: "2024-12-10",
    returned_date: "2024-12-10",
    purpose: "Troubleshooting jaringan cabang",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Masalah terselesaikan, kondisi baik.",
    asset_status_snapshot: "BORROWED",
  },

  // ── ast006: UPS APC ─────────────────────────────────────
  {
    id: "trx014",
    asset_id: "ast006",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "BORROW",
    date: "2024-02-10",
    return_date: "2024-02-20",
    returned_date: "2024-02-20",
    purpose: "Backup power ruang operasional",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes: "Baterai UPS mulai lemah, perlu penggantian segera.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx015",
    asset_id: "ast006",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "MAINTENANCE",
    date: "2025-01-15",
    return_date: "2025-01-30",
    returned_date: null,
    purpose: "Penggantian baterai & service rutin",
    status: "ACTIVE",
    condition_before: "MINOR_DAMAGE",
    condition_after: null,
    notes: "Baterai sudah dipesan, menunggu kedatangan.",
    return_notes: null,
    asset_status_snapshot: "MAINTENANCE",
  },

  // ── ast007: Laptop ASUS ──────────────────────────────────
  {
    id: "trx016",
    asset_id: "ast007",
    user_id: "u009",
    user_name: "Indah Permata",
    type: "BORROW",
    date: "2024-04-10",
    return_date: "2024-04-20",
    returned_date: "2024-04-19",
    purpose: "Rekrutmen karyawan baru",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Baik, lengkap.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx017",
    asset_id: "ast007",
    user_id: "u001",
    user_name: "Andi Pratama",
    type: "BORROW",
    date: "2025-01-05",
    return_date: "2025-01-12",
    returned_date: "2025-01-11",
    purpose: "Backup laptop utama rusak",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "",
    return_notes: "Oke, tidak ada masalah.",
    asset_status_snapshot: "AVAILABLE",
  },

  // ── ast008: Laptop Lenovo ThinkPad X1 ───────────────────
  {
    id: "trx018",
    asset_id: "ast008",
    user_id: "u010",
    user_name: "Joko Santoso",
    type: "BORROW",
    date: "2024-09-01",
    return_date: "2024-09-10",
    returned_date: "2024-09-10",
    purpose: "Rapat direksi luar kota",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "GOOD",
    notes: "Laptop direktur utama.",
    return_notes: "Kondisi sempurna.",
    asset_status_snapshot: "AVAILABLE",
  },
  {
    id: "trx019",
    asset_id: "ast008",
    user_id: "u010",
    user_name: "Joko Santoso",
    type: "BORROW",
    date: "2025-02-15",
    return_date: "2025-03-01",
    returned_date: null,
    purpose: "Perjalanan dinas ke Jakarta",
    status: "ACTIVE",
    condition_before: "GOOD",
    condition_after: null,
    notes: "",
    return_notes: null,
    asset_status_snapshot: "BORROWED",
  },

  // ── ast009: Laptop Toshiba (DELETED) ────────────────────
  {
    id: "trx020",
    asset_id: "ast009",
    user_id: "u011",
    user_name: "Khalid Fadli",
    type: "BORROW",
    date: "2023-03-10",
    return_date: "2023-03-20",
    returned_date: "2023-03-22",
    purpose: "Keperluan training internal",
    status: "RETURNED",
    condition_before: "GOOD",
    condition_after: "MINOR_DAMAGE",
    notes: "",
    return_notes: "Layar ada dead pixel di sudut kiri.",
    asset_status_snapshot: "BORROWED",
  },
  {
    id: "trx021",
    asset_id: "ast009",
    user_id: "u012",
    user_name: "Lina Sari",
    type: "BORROW",
    date: "2023-08-05",
    return_date: "2023-08-15",
    returned_date: "2023-08-16",
    purpose: "Kebutuhan sementara staf baru",
    status: "RETURNED",
    condition_before: "MINOR_DAMAGE",
    condition_after: "DAMAGED",
    notes: "Kondisi sudah tidak ideal.",
    return_notes:
      "Charger original hilang, tombol keyboard ada yang lepas. Tidak layak pakai.",
    asset_status_snapshot: "BORROWED",
  },
  {
    id: "trx022",
    asset_id: "ast009",
    user_id: "u007",
    user_name: "Gunawan Setiawan",
    type: "MAINTENANCE",
    date: "2023-09-01",
    return_date: "2023-09-15",
    returned_date: "2023-09-15",
    purpose: "Evaluasi & penghapusan aset tidak layak",
    status: "RETURNED",
    condition_before: "DAMAGED",
    condition_after: "DAMAGED",
    notes: "Sudah melalui proses BA penghapusan aset.",
    return_notes:
      "Aset dinyatakan tidak layak operasional. Direkomendasikan dihapus dari inventaris.",
    asset_status_snapshot: "DELETED",
  },
];

// ---- Configs ----
export const categoryConf = {
  LAPTOP: { label: "Laptop", color: "#2563eb", bg: "#eff6ff" },
  SERVER: { label: "Server", color: "#7c3aed", bg: "#f5f3ff" },
  DESKTOP: { label: "Desktop", color: "#0891b2", bg: "#ecfeff" },
  NETWORK: { label: "Network", color: "#059669", bg: "#ecfdf5" },
  UPS: { label: "UPS", color: "#d97706", bg: "#fffbeb" },
  OTHER: { label: "Lainnya", color: "#64748b", bg: "#f8fafc" },
};

export const statusConf = {
  AVAILABLE: {
    label: "Tersedia",
    color: "#16a34a",
    bg: "#dcfce7",
    dot: "#22c55e",
  },
  BORROWED: {
    label: "Dipinjam",
    color: "#d97706",
    bg: "#fef9c3",
    dot: "#f59e0b",
  },
  MAINTENANCE: {
    label: "Maintenance",
    color: "#dc2626",
    bg: "#fee2e2",
    dot: "#ef4444",
  },
  DELETED: {
    label: "Dihapus",
    color: "#64748b",
    bg: "#f1f5f9",
    dot: "#94a3b8",
  },
};

export const conditionConf = {
  GOOD: { label: "Baik", color: "#16a34a", bg: "#dcfce7" },
  MINOR_DAMAGE: { label: "Rusak Ringan", color: "#d97706", bg: "#fef9c3" },
  DAMAGED: { label: "Rusak Berat", color: "#dc2626", bg: "#fee2e2" },
};

export const trxTypeConf = {
  BORROW: { label: "Peminjaman", color: "#2563eb", bg: "#dbeafe" },
  MAINTENANCE: { label: "Maintenance", color: "#dc2626", bg: "#fee2e2" },
};

// ---- Formatters ----
export const fmtIDR = (n) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(n);

export const fmt = (d) => {
  if (!d) return "-";
  const [y, m, day] = d.split("-");
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Mei",
    "Jun",
    "Jul",
    "Agu",
    "Sep",
    "Okt",
    "Nov",
    "Des",
  ];
  return `${parseInt(day, 10)} ${months[parseInt(m, 10) - 1]} ${y}`;
};

export const isOverdue = (dateStr) => {
  if (!dateStr) return false;
  return new Date(dateStr) < new Date();
};
